### PR TITLE
Fixing/misc

### LINKED ISSUE #56: Items are disapearing
Hello, Items are disapearing after you die.If keepinventory is set true, each time you die, I receive a bow.

Solution: Try to clear inventory and regive items back to player on death.

Tested on 1.19.2

### PR DESCRIPTION
**Pull request by RedstoneFuture**
- Fix teleporting players to fallback spawn with server stop
- Fix twice calling of arena leave event (because of teleport)
- Fix #56 with using of newer methods to set the world gamerule - should work from 1.13.x - 1.19.x (The arena config option `keep_inventory` will change the `keepInventory` gamerule too.)
- Fix `max_spectators` calculation
- Fix warn `Nag author(s): '[Butzlabben]' of 'MissileWars' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).`

### CODE REVIEW

File: missilewars-plugin/src/main/java/de/butzlabben/missilewars/game/GameWorld.java [hunk 1]
```diff
@@ -134,8 +135,9 @@ public void load() {
             Logger.DEBUG.log("Loading new gameworld");
             World world = Bukkit.createWorld(new WorldCreator(worldName));
             Bukkit.getWorlds().add(world);
-            world.setGameRuleValue("doTileDrops", String.valueOf(game.getArena().isDoTileDrops()));
-            world.setGameRuleValue("keepInventory", String.valueOf(game.getArena().isKeepInventory()));
+
```
Comment (daniel-naegele) [inline missilewars-plugin/src/main/java/de/butzlabben/missilewars/game/GameWorld.java:138]: Does this also work on older versions like 1.13?

Comment (RedstoneFuture) [reply missilewars-plugin/src/main/java/de/butzlabben/missilewars/game/GameWorld.java:138]: Should work from 1.13.x - 1.19.x.
https://helpch.at/docs/1.13.1/org/bukkit/World.html#setGameRule-org.bukkit.GameRule-T-
